[fedora]
homelab1 ansible_host=192.168.86.8
homelab3 ansible_host=192.168.86.10
homelab5 ansible_host=192.168.86.12
homelab7 ansible_host=192.168.86.14

[proxmox_hosts]
proxmox1 ansible_host=192.168.86.20
proxmox2 ansible_host=192.168.86.21
proxmox3 ansible_host=192.168.86.22

[proxmox:children]
proxmox_hosts

[docker-hosts]
homelab3 ansible_host=192.168.86.10

[kubernetes-nodes]
homelab5 ansible_host=192.168.86.12
homelab7 ansible_host=192.168.86.14
homelab1 ansible_host=192.168.86.8


[all:vars]
ansible_user=rasmus
ansible_become=true
ansible_become_method=sudo
